In [2]:
import pandas as pd
import requests

In [4]:
response=requests.get("paste url here with your api key")

MissingSchema: Invalid URL 'paste url here with your api key': No scheme supplied. Perhaps you meant https://paste url here with your api key?

In [6]:
pd.DataFrame(response.json()['results'])

NameError: name 'response' is not defined

In [7]:
df=pd.DataFrame(response.json()['results']).head(2)[['id','title','overview','release_date','popularity','vote_count','vote_avg']

_IncompleteInputError: incomplete input (1765264175.py, line 1)

In [8]:
df.head()

NameError: name 'df' is not defined

In [10]:
df=pd.DataFrame()

In [12]:
df

Empty DataFrame
Columns: []
Index: []

In [14]:
for i in range(1,429):
    response=requests.get("paste url here with your api key".format(i))
    temp_df=df=pd.DataFrame(response.json()['results']).head(2)[['id','title','overview','release_date','popularity','vote_count','vote_avg']]
    df.append(temp_df,ignore_index=True)

MissingSchema: Invalid URL 'paste url here with your api key': No scheme supplied. Perhaps you meant https://paste url here with your api key?

In [15]:
df

Empty DataFrame
Columns: []
Index: []

In [16]:
df.shape()

TypeError: 'tuple' object is not callable

## data converted to CSV

In [17]:
df.to_csv('movies.csv')

## cells did not execute bcz no api key was generated but the logic and code structure remains intact